import groovy.json.*
args_map = [version:"1.$BUILD_NUMBER"]
print "Build number: "+BUILD_NUMBER
version = BUILD_NUMBER
print "version: "+version

pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        sh 'tar -zcvf public.tar.gz public'
      }
    }
    stage("OCI Upload Artifact") {
        steps {
          OCIUploadArtifact(credentialsId: '',
          uploadArtifactDetailsList: [[artifactPath: 'public.tar.gz',
          repositoryId: '',
          repositoryType: 'GENERIC',
          sourcePath: 'public.tar.gz',
          version: "1.$BUILD_NUMBER"],
          [artifactPath: 'deployment_spec.yaml',
          repositoryId: '',
          repositoryType: 'GENERIC',
          sourcePath: 'deployment_spec.yaml',
          version: "1.$BUILD_NUMBER"]
          ])
        }
    }
    stage('Trigger Deployment') {
        steps {
          OCIDeployment(argumentVal: JsonOutput.toJson(args_map),
          credentialsId: '',
          displayName: "testDeployment${BUILD_NUMBER}",
          endpoint: 'https://devops.ca-toronto-1.oci.oraclecloud.com',
          pipelineId: '',
          pollingConfig: [timeoutSeconds: 600, "pollingIntervalSeconds" : 5], executionMode: 'SYNC'
          )
      }
    }  
  }
}